version: "3"
services:
  erika:
    image: erika:${ERIKA_VERSION}
    container_name: erika
    ports:
      - 14514:${HTTP_PORT}
    volumes:
      - ${PWD}/log:${ERIKA_LOG_DIR}
      - ${PWD}/task:${ERIKA_TASK_DIR}
      - ${ERIKA_GIT_DIR}:${ERIKA_GIT_DIR}
    restart: always